### ISSUE TITLE
Update starter app to Bootstrap 5.3.x and eliminate as much custom css as possible

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-forge#346]
`grails create-app` creates a nice starter example, but has a lot of css rules that are too generalized and can't be used in new projects.   If we are going to utilize bootstrap, we should try to leverage Bootstrap classes where possible and limit the amount of CSS in the generated app.

I propose the following:
1. Update Bootstrap to the latest version
2. Make a package.json in [grails-forge-core](https://github.com/grails/grails-forge/blob/6.2.x/grails-forge-core) file that will update bootstrap to the latest version using the `npm run` command 
3. Minimize the usage of any custom css to as little as possible and utilize [bootstrap-icons](https://icons.getbootstrap.com) where possible.  Current [custom css](https://github.com/grails/grails-forge/blob/6.2.x/grails-forge-core/src/main/resources/assets/stylesheets/main.css) 2000 lines of code 👎 
4. Update [g:paginate and g:sortableColumn](https://github.com/grails/grails-gsp/blob/6.2.x/grails-plugin-gsp/src/main/groovy/org/grails/plugins/web/taglib/UrlMappingTagLib.groovy) to allow overriding of class names so that bootstrap classes could be used instead. 
5. Collaborate with [fields plugin tags ](https://github.com/gpc/fields)to allow overriding of class names instead of having to create a `_wrapper.gsp` in order to use bootstrap classes.  Out of the box, `<f:all `should be able to render a clean bootstrap 5 form representation without need for extensive css.

https://getbootstrap.com/docs/5.3/forms/layout/

**Comment by osscontributor** [comment]
> grails create-app creates a nice starter example, but has a lot of css rules that are too generalized and can't be used in new projects.

What kinds of rules can't be used in new projects?

**Comment by jamesfredley** [comment]
I think we should also explore pulling `bootstrap` and `jquery` from webjars instead of living in /assets/

implementation "org.webjars.npm:bootstrap:5.3.3"
implementation "org.webjars.npm:jquery:3.7.1"

<asset:javascript src="webjars/jquery/3.7.1/dist/jquery.min.js" />
<asset:stylesheet src="webjars/bootstrap/5.3.3/dist/css/bootstrap.min.css" />

**Comment by codeconsole** [comment]
> I think we should also explore pulling `bootstrap` and `jquery` from webjars instead of living in /assets/
> 
> implementation "org.webjars.npm:bootstrap:5.3.3" implementation "org.webjars.npm:jquery:3.7.1"
> 
> <asset:javascript src="webjars/jquery/3.7.1/dist/jquery.min.js" /> <asset:stylesheet src="webjars/bootstrap/5.3.3/dist/css/bootstrap.min.css" />

Does the asset pipeline pull them out at build time?

**Comment by codeconsole** [comment]
@jamesfredley just adding 
```gradle
implementation "org.webjars.npm:bootstrap:5.3.3"
```

to `build.gradle` results in:

```
% ./gradlew clean bootJar
bootstrap.esm.unminified.js:7:0: ERROR - [JSC_INVALID_MODULE_PATH] Invalid module path "@popperjs/core" for resolution mode "BROWSER"
  7| import * as Popper from '@popperjs/core';
     ^

1 error(s), 1 warning(s)
Closure uglify JS Exception
asset.pipeline.processors.MinifyException: [JSC_INVALID_MODULE_PATH. Invalid module path "@popperjs/core" for resolution mode "BROWSER" at bootstrap.esm.unminified.js line 7 : 0]
        at asset.pipeline.processors.ClosureCompilerProcessor.process(ClosureCompilerProcessor.groovy:81)
        at asset.pipeline.processors.ClosureCompilerProcessor$process.call(Unknown Source)
        at asset.pipeline.AssetCompiler$_compile_closure4.doCall$original(AssetCompiler.groovy:171)
        at asset.pipeline.AssetCompiler$_compile_closure4.doCall(AssetCompiler.groovy)
        at java.base@21.0.4/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base@21.0.4/java.lang.reflect.Method.invoke(Method.java:580)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
        at groovy.lang.Closure.call(Closure.java:427)
```

**Comment by codeconsole** [comment]
> I think we should also explore pulling `bootstrap` and `jquery` from webjars instead of living in /assets/
> 
> implementation "org.webjars.npm:bootstrap:5.3.3" implementation "org.webjars.npm:jquery:3.7.1"
> 
> <asset:javascript src="webjars/jquery/3.7.1/dist/jquery.min.js" /> <asset:stylesheet src="webjars/bootstrap/5.3.3/dist/css/bootstrap.min.css" />

I got that working
