### ISSUE TITLE
Problem Generating Grails Wrapper

### ISSUE THREAD

**Issue by jeffscottbrown** [grails/grails-forge#381]
```
brownj@Jeff-Brown-Unity t % sdk use grails 6.2.1

Using grails version 6.2.1 in this shell.
brownj@Jeff-Brown-Unity t % 
brownj@Jeff-Brown-Unity t % grails --version
Grails Version: 6.2.1
JVM Version: 17.0.9
brownj@Jeff-Brown-Unity t % 
brownj@Jeff-Brown-Unity t % 
brownj@Jeff-Brown-Unity t % grails create-app -f grails-wrapper someappname
| Error Resource not found for url: null
```

The problem does not seem to manifest if I use the CLI from https://github.com/grails/grails-forge/releases/download/v6.2.1/grails-cli-6.2.1.zip.

**Comment by jeffscottbrown** [comment]
A relevant PR: https://github.com/grails/grails-forge/pull/360/files

**Comment by jamesfredley** [comment]
Also not occurring on start.grails.org or using Grails Application Forge in IntelliJ.

**Comment by jamesfredley** [comment]
@jeffscottbrown Please retest this with the latest snapshot from: https://github.com/grails/grails-forge/actions/runs/11242927885#artifacts

**Comment by jamesfredley** [comment]
@jeffscottbrown can you re-test this with the latest snapshot?

https://github.com/grails/grails-forge/actions/runs/11275038680/artifacts/2040471171

**Comment by jeffscottbrown** [comment]
Would you expect the darwin amd64 binary to work on Apple Silicon?

'> brownj@Jeff-Brown-Unity t % sdk use java 17.0.7-zulu 
> 
> Using java version 17.0.7-zulu in this shell.
> brownj@Jeff-Brown-Unity t % 
> brownj@Jeff-Brown-Unity t % 
> brownj@Jeff-Brown-Unity t % sdk use grails  6.2.1
> 
> Using grails version 6.2.1 in this shell.
> brownj@Jeff-Brown-Unity t % 
> brownj@Jeff-Brown-Unity t % 
> brownj@Jeff-Brown-Unity t % which grails
> /Users/brownj/Downloads/grails-darwin-amd64-snapshot/bin/grails
> brownj@Jeff-Brown-Unity t % 
> brownj@Jeff-Brown-Unity t % 
> brownj@Jeff-Brown-Unity t % grails create-app -f grails-wrapper someappname
> | Error Resource not found for url: null

> % grails --version
> Grails Version: 6.2.2-SNAPSHOT
> JVM Version: 11.0.20
>

**Comment by jeffscottbrown** [comment]
@jamesfredley Does that command working for you?

**Comment by jamesfredley** [comment]
```
grails> create-app -f grails-wrapper test --stacktrace
| Error Resource not found for url: null
java.lang.NullPointerException: Resource not found for url: null
        at java.base@11.0.20/java.util.Objects.requireNonNull(Objects.java:246)
        at org.grails.forge.template.URLTemplate.<init>(URLTemplate.java:36)
        at org.grails.forge.template.URLTemplate.<init>(URLTemplate.java:31)
        at org.grails.forge.template.BinaryTemplate.<init>(BinaryTemplate.java:23)
        at org.grails.forge.feature.grailsWrapper.GrailsWrapper.apply(GrailsWrapper.java:53)
        at org.grails.forge.application.generator.GeneratorContext.applyFeatures(GeneratorContext.java:257)
        at org.grails.forge.application.generator.DefaultProjectGenerator.generate(DefaultProjectGenerator.java:96)
        at org.grails.forge.application.generator.DefaultProjectGenerator.generate(DefaultProjectGenerator.java:72)
        at org.grails.forge.cli.command.CreateCommand.generate(CreateCommand.java:125)
        at org.grails.forge.cli.command.CreateCommand.call(CreateCommand.java:112)
        at org.grails.forge.cli.command.CreateCommand.call(CreateCommand.java:38)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.grails.forge.cli.Application.execute(Application.java:99)
        at org.grails.forge.cli.InteractiveShell.start(InteractiveShell.java:89)
        at org.grails.forge.cli.Application.main(Application.java:83)
```

**Comment by jamesfredley** [comment]
Resolved by https://github.com/grails/grails-forge/pull/393

Latest binaries:  https://github.com/grails/grails-forge/actions/runs/11282245601#artifacts
