### ISSUE TITLE
Linux Graalvm Native Image Fails

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-forge#476]
https://github.com/grails/grails-forge/actions/runs/12476328598/job/34821043870

Tried twice.

```
[1/8] Initializing...                                                                                    (0.0s @ 0.16GB)
------------------------------------------------------------------------------------------------------------------------
                        0.7s (10.6% of total time) in 20 GCs | Peak RSS: 0.[68](https://github.com/grails/grails-forge/actions/runs/12476328598/job/34821043870#step:6:69)GB | CPU load: 3.21
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/runner/work/grails-forge/grails-forge/grails-cli/build/native/nativeCompile/svm_err_b_20241224T031902.[70](https://github.com/grails/grails-forge/actions/runs/12476328598/job/34821043870#step:6:71)0_pid2704.md (build_info)
========================================================================================================================
Failed generating 'grails' after 5.7s.

The build process encountered an unexpected error:

com.oracle.svm.core.util.VMError$HostedError: Unable to run '/tmp/SVM-2827766744210530730/RISCV64LibCHelperDirectives' to compute offsets in C data structures. Is it possible that your antivirus software interferes and puts the resulting file into quarantine?
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:80)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.makeQuery(CAnnotationProcessor.java:142)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:118)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:559)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1[71](https://github.com/grails/grails-forge/actions/runs/12476328598/job/34821043870#step:6:72)2)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1171)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:934)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:579)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
Caused by: java.io.IOException: Cannot run program "/tmp/SVM-2827766744210530[73](https://github.com/grails/grails-forge/actions/runs/12476328598/job/34821043870#step:6:74)0/RISCV64LibCHelperDirectives" (in directory "/tmp/SVM-2827766744210530730"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.makeQuery(CAnnotationProcessor.java:133)
	... 11 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 13 more


> Task :grails-cli:nativeCompile FAILED

[Incubating] Problems report is available at: file:///home/runner/work/grails-forge/grails-forge/build/reports/problems/problems-report.html
FAILURE: Build failed with an exception.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.11.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
19 actionable tasks: 1 executed, 18 up-to-date

* What went wrong:
Execution failed for task ':grails-cli:nativeCompile'.
> Process 'command '/opt/hostedtoolcache/graalvm-community-jdk-17.0.9_linux-x64_bin/17.0.9/x64/graalvm-community-openjdk-17.0.9+9.1/bin/native-image'' finished with non-zero exit value 1
```

**Comment by jamesfredley** [comment]
Had to remove musl to resolve this error

```
              native-image-musl: 'true'

      - name: "📸 Build the Native Image (with libc=musl)"
        run: ./gradlew grails-cli:nativeCompile --no-daemon -Pmusl
```
